<?php
/**
 * SubscriptionApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SubscriptionApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionApi
{

    /**
     * API Client
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://localhost/');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return SubscriptionApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * getSubscriptions
     *
     * Get list of subscriptions
     *
     * @param int $page Page number to get (optional)
     * @param int $size Page size to use (optional)
     * @param string $search Optional search expression (optional)
     * @param string $sort Optional sorting expression (optional)
     * @return \Swagger\Client\Model\SubscriptionSearch
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptions($page = null, $size = null, $search = null, $sort = null)
    {
        list($response, $statusCode, $httpHeader) = $this->getSubscriptionsWithHttpInfo ($page, $size, $search, $sort);
        return $response; 
    }


    /**
     * getSubscriptionsWithHttpInfo
     *
     * Get list of subscriptions
     *
     * @param int $page Page number to get (optional)
     * @param int $size Page size to use (optional)
     * @param string $search Optional search expression (optional)
     * @param string $sort Optional sorting expression (optional)
     * @return Array of \Swagger\Client\Model\SubscriptionSearch, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionsWithHttpInfo($page = null, $size = null, $search = null, $sort = null)
    {
        
  
        // parse inputs
        $resourcePath = "/v1/subscription";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($page !== null) {
            $queryParams['page'] = $this->apiClient->getSerializer()->toQueryValue($page);
        }// query params
        
        if ($size !== null) {
            $queryParams['size'] = $this->apiClient->getSerializer()->toQueryValue($size);
        }// query params
        
        if ($search !== null) {
            $queryParams['search'] = $this->apiClient->getSerializer()->toQueryValue($search);
        }// query params
        
        if ($sort !== null) {
            $queryParams['sort'] = $this->apiClient->getSerializer()->toQueryValue($sort);
        }
        
        
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\SubscriptionSearch'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SubscriptionSearch', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SubscriptionSearch', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * createSubscriptionJson
     *
     * Create subscription
     *
     * @param \Swagger\Client\Model\CreateSubscription $body  (optional)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionJson($body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->createSubscriptionJsonWithHttpInfo ($body);
        return $response; 
    }


    /**
     * createSubscriptionJsonWithHttpInfo
     *
     * Create subscription
     *
     * @param \Swagger\Client\Model\CreateSubscription $body  (optional)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionJsonWithHttpInfo($body = null)
    {
        
  
        // parse inputs
        $resourcePath = "/v1/subscription";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getSubscription
     *
     * Get subscription
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscription($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->getSubscriptionWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * getSubscriptionWithHttpInfo
     *
     * Get subscription
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling getSubscription');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * cancelSubscription
     *
     * Cancel subscription
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function cancelSubscription($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->cancelSubscriptionWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * cancelSubscriptionWithHttpInfo
     *
     * Cancel subscription
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function cancelSubscriptionWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling cancelSubscription');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/cancel";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * cancelChangePlan
     *
     * Cancel pending plan change
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function cancelChangePlan($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->cancelChangePlanWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * cancelChangePlanWithHttpInfo
     *
     * Cancel pending plan change
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function cancelChangePlanWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling cancelChangePlan');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/cancel_change_plan";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * changeNextPeriodStartJson
     *
     * Change next renewal date
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\ChangeNextPeriodStart $body  (optional)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function changeNextPeriodStartJson($handle, $body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->changeNextPeriodStartJsonWithHttpInfo ($handle, $body);
        return $response; 
    }


    /**
     * changeNextPeriodStartJsonWithHttpInfo
     *
     * Change next renewal date
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\ChangeNextPeriodStart $body  (optional)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function changeNextPeriodStartJsonWithHttpInfo($handle, $body = null)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling changeNextPeriodStartJson');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/change_next_period_start";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * changePlanJson
     *
     * Change plan
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\ChangePlan $body  (optional)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function changePlanJson($handle, $body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->changePlanJsonWithHttpInfo ($handle, $body);
        return $response; 
    }


    /**
     * changePlanJsonWithHttpInfo
     *
     * Change plan
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\ChangePlan $body  (optional)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function changePlanJsonWithHttpInfo($handle, $body = null)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling changePlanJson');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/change_plan";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getSubscriptionDiscounts
     *
     * Get subscription discounts
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\SubscriptionDiscount[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionDiscounts($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->getSubscriptionDiscountsWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * getSubscriptionDiscountsWithHttpInfo
     *
     * Get subscription discounts
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\SubscriptionDiscount[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionDiscountsWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling getSubscriptionDiscounts');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/discount";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\SubscriptionDiscount[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SubscriptionDiscount[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SubscriptionDiscount[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * createSubscriptionDiscount
     *
     * Add subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\CreateSubscriptionDiscount $body  (optional)
     * @return \Swagger\Client\Model\SubscriptionDiscount
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionDiscount($handle, $body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->createSubscriptionDiscountWithHttpInfo ($handle, $body);
        return $response; 
    }


    /**
     * createSubscriptionDiscountWithHttpInfo
     *
     * Add subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\CreateSubscriptionDiscount $body  (optional)
     * @return Array of \Swagger\Client\Model\SubscriptionDiscount, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionDiscountWithHttpInfo($handle, $body = null)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling createSubscriptionDiscount');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/discount";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\SubscriptionDiscount'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SubscriptionDiscount', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SubscriptionDiscount', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getSubscriptionDiscount
     *
     * Get subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param string $sd_handle Subscription discount handle (required)
     * @return \Swagger\Client\Model\SubscriptionDiscount
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionDiscount($handle, $sd_handle)
    {
        list($response, $statusCode, $httpHeader) = $this->getSubscriptionDiscountWithHttpInfo ($handle, $sd_handle);
        return $response; 
    }


    /**
     * getSubscriptionDiscountWithHttpInfo
     *
     * Get subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param string $sd_handle Subscription discount handle (required)
     * @return Array of \Swagger\Client\Model\SubscriptionDiscount, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionDiscountWithHttpInfo($handle, $sd_handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling getSubscriptionDiscount');
        }
        // verify the required parameter 'sd_handle' is set
        if ($sd_handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sd_handle when calling getSubscriptionDiscount');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/discount/{sdHandle}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }// path params
        
        if ($sd_handle !== null) {
            $resourcePath = str_replace(
                "{" . "sdHandle" . "}",
                $this->apiClient->getSerializer()->toPathValue($sd_handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\SubscriptionDiscount'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SubscriptionDiscount', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SubscriptionDiscount', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteSubscriptionDiscount
     *
     * Delete subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param string $sd_handle Subscription discount handle (required)
     * @return \Swagger\Client\Model\SubscriptionDiscount
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteSubscriptionDiscount($handle, $sd_handle)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteSubscriptionDiscountWithHttpInfo ($handle, $sd_handle);
        return $response; 
    }


    /**
     * deleteSubscriptionDiscountWithHttpInfo
     *
     * Delete subscription discount
     *
     * @param string $handle Subscription handle (required)
     * @param string $sd_handle Subscription discount handle (required)
     * @return Array of \Swagger\Client\Model\SubscriptionDiscount, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteSubscriptionDiscountWithHttpInfo($handle, $sd_handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling deleteSubscriptionDiscount');
        }
        // verify the required parameter 'sd_handle' is set
        if ($sd_handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sd_handle when calling deleteSubscriptionDiscount');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/discount/{sdHandle}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "DELETE";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }// path params
        
        if ($sd_handle !== null) {
            $resourcePath = str_replace(
                "{" . "sdHandle" . "}",
                $this->apiClient->getSerializer()->toPathValue($sd_handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\SubscriptionDiscount'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SubscriptionDiscount', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SubscriptionDiscount', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * expire
     *
     * Expire subscription
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function expire($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->expireWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * expireWithHttpInfo
     *
     * Expire subscription
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function expireWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling expire');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/expire";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * intervalAmount
     *
     * Calculate interval amount
     *
     * @param string $handle Subscription handle (required)
     * @param string $from From date on the form yyyy-MM-dd (required)
     * @param string $to To date on the form yyyy-MM-dd (required)
     * @return \Swagger\Client\Model\IntervalAmount
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function intervalAmount($handle, $from, $to)
    {
        list($response, $statusCode, $httpHeader) = $this->intervalAmountWithHttpInfo ($handle, $from, $to);
        return $response; 
    }


    /**
     * intervalAmountWithHttpInfo
     *
     * Calculate interval amount
     *
     * @param string $handle Subscription handle (required)
     * @param string $from From date on the form yyyy-MM-dd (required)
     * @param string $to To date on the form yyyy-MM-dd (required)
     * @return Array of \Swagger\Client\Model\IntervalAmount, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function intervalAmountWithHttpInfo($handle, $from, $to)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling intervalAmount');
        }
        // verify the required parameter 'from' is set
        if ($from === null) {
            throw new \InvalidArgumentException('Missing the required parameter $from when calling intervalAmount');
        }
        // verify the required parameter 'to' is set
        if ($to === null) {
            throw new \InvalidArgumentException('Missing the required parameter $to when calling intervalAmount');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/interval_amount";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($from !== null) {
            $queryParams['from'] = $this->apiClient->getSerializer()->toQueryValue($from);
        }// query params
        
        if ($to !== null) {
            $queryParams['to'] = $this->apiClient->getSerializer()->toQueryValue($to);
        }
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\IntervalAmount'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\IntervalAmount', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\IntervalAmount', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * createSubscriptionInvoice
     *
     * Create invoice ondemand for subscription
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\CreateSubscriptionInvoice $body  (optional)
     * @return \Swagger\Client\Model\Invoice
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionInvoice($handle, $body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->createSubscriptionInvoiceWithHttpInfo ($handle, $body);
        return $response; 
    }


    /**
     * createSubscriptionInvoiceWithHttpInfo
     *
     * Create invoice ondemand for subscription
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\CreateSubscriptionInvoice $body  (optional)
     * @return Array of \Swagger\Client\Model\Invoice, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createSubscriptionInvoiceWithHttpInfo($handle, $body = null)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling createSubscriptionInvoice');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/invoice";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Invoice'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Invoice', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Invoice', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getSubscriptionPaymentMethods
     *
     * Get payment methods
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\PaymentMethods
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionPaymentMethods($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->getSubscriptionPaymentMethodsWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * getSubscriptionPaymentMethodsWithHttpInfo
     *
     * Get payment methods
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\PaymentMethods, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getSubscriptionPaymentMethodsWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling getSubscriptionPaymentMethods');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/payment_method";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\PaymentMethods'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethods', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethods', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * removeAllPaymentMethods
     *
     * Remove all payment methods
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\PaymentMethods
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function removeAllPaymentMethods($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->removeAllPaymentMethodsWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * removeAllPaymentMethodsWithHttpInfo
     *
     * Remove all payment methods
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\PaymentMethods, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function removeAllPaymentMethodsWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling removeAllPaymentMethods');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/payment_method";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "DELETE";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\PaymentMethods'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethods', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethods', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * setCardPaymentMethodJson
     *
     * Set card payment method
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\SetCardPaymentMethod $body  (optional)
     * @return \Swagger\Client\Model\PaymentMethods
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function setCardPaymentMethodJson($handle, $body = null)
    {
        list($response, $statusCode, $httpHeader) = $this->setCardPaymentMethodJsonWithHttpInfo ($handle, $body);
        return $response; 
    }


    /**
     * setCardPaymentMethodJsonWithHttpInfo
     *
     * Set card payment method
     *
     * @param string $handle Subscription handle (required)
     * @param \Swagger\Client\Model\SetCardPaymentMethod $body  (optional)
     * @return Array of \Swagger\Client\Model\PaymentMethods, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function setCardPaymentMethodJsonWithHttpInfo($handle, $body = null)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling setCardPaymentMethodJson');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/payment_method/card";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\PaymentMethods'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethods', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethods', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * removePaymentMethod
     *
     * Remove payment method
     *
     * @param string $handle Subscription handle (required)
     * @param string $method_id Payment method id (required)
     * @return \Swagger\Client\Model\PaymentMethods
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function removePaymentMethod($handle, $method_id)
    {
        list($response, $statusCode, $httpHeader) = $this->removePaymentMethodWithHttpInfo ($handle, $method_id);
        return $response; 
    }


    /**
     * removePaymentMethodWithHttpInfo
     *
     * Remove payment method
     *
     * @param string $handle Subscription handle (required)
     * @param string $method_id Payment method id (required)
     * @return Array of \Swagger\Client\Model\PaymentMethods, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function removePaymentMethodWithHttpInfo($handle, $method_id)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling removePaymentMethod');
        }
        // verify the required parameter 'method_id' is set
        if ($method_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $method_id when calling removePaymentMethod');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/payment_method/{method_id}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "DELETE";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }// path params
        
        if ($method_id !== null) {
            $resourcePath = str_replace(
                "{" . "method_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($method_id),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\PaymentMethods'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethods', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethods', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * uncancel
     *
     * Uncancel subscription
     *
     * @param string $handle Subscription handle (required)
     * @return \Swagger\Client\Model\Subscription
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function uncancel($handle)
    {
        list($response, $statusCode, $httpHeader) = $this->uncancelWithHttpInfo ($handle);
        return $response; 
    }


    /**
     * uncancelWithHttpInfo
     *
     * Uncancel subscription
     *
     * @param string $handle Subscription handle (required)
     * @return Array of \Swagger\Client\Model\Subscription, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function uncancelWithHttpInfo($handle)
    {
        
        // verify the required parameter 'handle' is set
        if ($handle === null) {
            throw new \InvalidArgumentException('Missing the required parameter $handle when calling uncancel');
        }
  
        // parse inputs
        $resourcePath = "/v1/subscription/{handle}/uncancel";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        
        
        // path params
        
        if ($handle !== null) {
            $resourcePath = str_replace(
                "{" . "handle" . "}",
                $this->apiClient->getSerializer()->toPathValue($handle),
                $resourcePath
            );
        }
        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Subscription'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\Subscription', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Subscription', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
