<?php
/**
 * CreateSubscriptionDiscount
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * CreateSubscriptionDiscount Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateSubscriptionDiscount implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'handle' => 'string',
        'discount' => 'string',
        'name' => 'string',
        'description' => 'string',
        'amount' => 'int',
        'percentage' => 'int',
        'apply_to' => 'string[]',
        'fixed_count' => 'int',
        'fixed_period_unit' => 'string',
        'fixed_period' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'handle' => 'handle',
        'discount' => 'discount',
        'name' => 'name',
        'description' => 'description',
        'amount' => 'amount',
        'percentage' => 'percentage',
        'apply_to' => 'apply_to',
        'fixed_count' => 'fixed_count',
        'fixed_period_unit' => 'fixed_period_unit',
        'fixed_period' => 'fixed_period'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'handle' => 'setHandle',
        'discount' => 'setDiscount',
        'name' => 'setName',
        'description' => 'setDescription',
        'amount' => 'setAmount',
        'percentage' => 'setPercentage',
        'apply_to' => 'setApplyTo',
        'fixed_count' => 'setFixedCount',
        'fixed_period_unit' => 'setFixedPeriodUnit',
        'fixed_period' => 'setFixedPeriod'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'handle' => 'getHandle',
        'discount' => 'getDiscount',
        'name' => 'getName',
        'description' => 'getDescription',
        'amount' => 'getAmount',
        'percentage' => 'getPercentage',
        'apply_to' => 'getApplyTo',
        'fixed_count' => 'getFixedCount',
        'fixed_period_unit' => 'getFixedPeriodUnit',
        'fixed_period' => 'getFixedPeriod'
    );
  
    
    /**
      * $handle Per subscription unique handle for the subscription discount.
      * @var string
      */
    protected $handle;
    
    /**
      * $discount Discount for subscription discount
      * @var string
      */
    protected $discount;
    
    /**
      * $name Optional name overrding discount name
      * @var string
      */
    protected $name;
    
    /**
      * $description Optional description overriding discount description
      * @var string
      */
    protected $description;
    
    /**
      * $amount Optional overriding fixed amount from discount
      * @var int
      */
    protected $amount;
    
    /**
      * $percentage Optional percentage overriding percentage from discount
      * @var int
      */
    protected $percentage;
    
    /**
      * $apply_to Optional overriding discount settings
      * @var string[]
      */
    protected $apply_to;
    
    /**
      * $fixed_count Optioanl overriding discount settings
      * @var int
      */
    protected $fixed_count;
    
    /**
      * $fixed_period_unit Optioanl overriding discount settings
      * @var string
      */
    protected $fixed_period_unit;
    
    /**
      * $fixed_period Optioanl overriding discount settings
      * @var int
      */
    protected $fixed_period;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->handle = $data["handle"];
            $this->discount = $data["discount"];
            $this->name = $data["name"];
            $this->description = $data["description"];
            $this->amount = $data["amount"];
            $this->percentage = $data["percentage"];
            $this->apply_to = $data["apply_to"];
            $this->fixed_count = $data["fixed_count"];
            $this->fixed_period_unit = $data["fixed_period_unit"];
            $this->fixed_period = $data["fixed_period"];
        }
    }
    
    /**
     * Gets handle
     * @return string
     */
    public function getHandle()
    {
        return $this->handle;
    }
  
    /**
     * Sets handle
     * @param string $handle Per subscription unique handle for the subscription discount.
     * @return $this
     */
    public function setHandle($handle)
    {
        
        $this->handle = $handle;
        return $this;
    }
    
    /**
     * Gets discount
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }
  
    /**
     * Sets discount
     * @param string $discount Discount for subscription discount
     * @return $this
     */
    public function setDiscount($discount)
    {
        
        $this->discount = $discount;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name Optional name overrding discount name
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
  
    /**
     * Sets description
     * @param string $description Optional description overriding discount description
     * @return $this
     */
    public function setDescription($description)
    {
        
        $this->description = $description;
        return $this;
    }
    
    /**
     * Gets amount
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }
  
    /**
     * Sets amount
     * @param int $amount Optional overriding fixed amount from discount
     * @return $this
     */
    public function setAmount($amount)
    {
        
        $this->amount = $amount;
        return $this;
    }
    
    /**
     * Gets percentage
     * @return int
     */
    public function getPercentage()
    {
        return $this->percentage;
    }
  
    /**
     * Sets percentage
     * @param int $percentage Optional percentage overriding percentage from discount
     * @return $this
     */
    public function setPercentage($percentage)
    {
        
        $this->percentage = $percentage;
        return $this;
    }
    
    /**
     * Gets apply_to
     * @return string[]
     */
    public function getApplyTo()
    {
        return $this->apply_to;
    }
  
    /**
     * Sets apply_to
     * @param string[] $apply_to Optional overriding discount settings
     * @return $this
     */
    public function setApplyTo($apply_to)
    {
        
        $this->apply_to = $apply_to;
        return $this;
    }
    
    /**
     * Gets fixed_count
     * @return int
     */
    public function getFixedCount()
    {
        return $this->fixed_count;
    }
  
    /**
     * Sets fixed_count
     * @param int $fixed_count Optioanl overriding discount settings
     * @return $this
     */
    public function setFixedCount($fixed_count)
    {
        
        $this->fixed_count = $fixed_count;
        return $this;
    }
    
    /**
     * Gets fixed_period_unit
     * @return string
     */
    public function getFixedPeriodUnit()
    {
        return $this->fixed_period_unit;
    }
  
    /**
     * Sets fixed_period_unit
     * @param string $fixed_period_unit Optioanl overriding discount settings
     * @return $this
     */
    public function setFixedPeriodUnit($fixed_period_unit)
    {
        $allowed_values = array("months", "days");
        if (!in_array($fixed_period_unit, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'fixed_period_unit', must be one of 'months', 'days'");
        }
        $this->fixed_period_unit = $fixed_period_unit;
        return $this;
    }
    
    /**
     * Gets fixed_period
     * @return int
     */
    public function getFixedPeriod()
    {
        return $this->fixed_period;
    }
  
    /**
     * Sets fixed_period
     * @param int $fixed_period Optioanl overriding discount settings
     * @return $this
     */
    public function setFixedPeriod($fixed_period)
    {
        
        $this->fixed_period = $fixed_period;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
