<?php
/**
 * CreateCustomerInvoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * CreateCustomerInvoice Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateCustomerInvoice implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'ref' => 'string',
        'order_lines' => '\Swagger\Client\Model\CreateOrderLine[]',
        'manual_transfer' => '\Swagger\Client\Model\ManualSettleTransfer',
        'payment_method' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'ref' => 'ref',
        'order_lines' => 'order_lines',
        'manual_transfer' => 'manual_transfer',
        'payment_method' => 'payment_method'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'ref' => 'setRef',
        'order_lines' => 'setOrderLines',
        'manual_transfer' => 'setManualTransfer',
        'payment_method' => 'setPaymentMethod'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'ref' => 'getRef',
        'order_lines' => 'getOrderLines',
        'manual_transfer' => 'getManualTransfer',
        'payment_method' => 'getPaymentMethod'
    );
  
    
    /**
      * $ref Optional reference to avoid double creations. Only one invoice can be created per reference.
      * @var string
      */
    protected $ref;
    
    /**
      * $order_lines Orderlines for the invoice
      * @var \Swagger\Client\Model\CreateOrderLine[]
      */
    protected $order_lines;
    
    /**
      * $manual_transfer Optional manual tranfer. If given the invoice will be settled using the manual transfer transaction.
      * @var \Swagger\Client\Model\ManualSettleTransfer
      */
    protected $manual_transfer;
    
    /**
      * $payment_method Payment method id to use for invoice. Must be provided if no manual transfer is given.
      * @var string
      */
    protected $payment_method;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->ref = $data["ref"];
            $this->order_lines = $data["order_lines"];
            $this->manual_transfer = $data["manual_transfer"];
            $this->payment_method = $data["payment_method"];
        }
    }
    
    /**
     * Gets ref
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }
  
    /**
     * Sets ref
     * @param string $ref Optional reference to avoid double creations. Only one invoice can be created per reference.
     * @return $this
     */
    public function setRef($ref)
    {
        
        $this->ref = $ref;
        return $this;
    }
    
    /**
     * Gets order_lines
     * @return \Swagger\Client\Model\CreateOrderLine[]
     */
    public function getOrderLines()
    {
        return $this->order_lines;
    }
  
    /**
     * Sets order_lines
     * @param \Swagger\Client\Model\CreateOrderLine[] $order_lines Orderlines for the invoice
     * @return $this
     */
    public function setOrderLines($order_lines)
    {
        
        $this->order_lines = $order_lines;
        return $this;
    }
    
    /**
     * Gets manual_transfer
     * @return \Swagger\Client\Model\ManualSettleTransfer
     */
    public function getManualTransfer()
    {
        return $this->manual_transfer;
    }
  
    /**
     * Sets manual_transfer
     * @param \Swagger\Client\Model\ManualSettleTransfer $manual_transfer Optional manual tranfer. If given the invoice will be settled using the manual transfer transaction.
     * @return $this
     */
    public function setManualTransfer($manual_transfer)
    {
        
        $this->manual_transfer = $manual_transfer;
        return $this;
    }
    
    /**
     * Gets payment_method
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }
  
    /**
     * Sets payment_method
     * @param string $payment_method Payment method id to use for invoice. Must be provided if no manual transfer is given.
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        
        $this->payment_method = $payment_method;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
