<?php
/**
 * UpdateWebhookSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * UpdateWebhookSettings Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateWebhookSettings implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'urls' => 'string[]',
        'username' => 'string',
        'password' => 'string',
        'disabled' => 'bool',
        'alert_emails' => 'string[]',
        'alert_count' => 'int'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'urls' => 'urls',
        'username' => 'username',
        'password' => 'password',
        'disabled' => 'disabled',
        'alert_emails' => 'alert_emails',
        'alert_count' => 'alert_count'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'urls' => 'setUrls',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'disabled' => 'setDisabled',
        'alert_emails' => 'setAlertEmails',
        'alert_count' => 'setAlertCount'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'urls' => 'getUrls',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'disabled' => 'getDisabled',
        'alert_emails' => 'getAlertEmails',
        'alert_count' => 'getAlertCount'
    );
  
    
    /**
      * $urls Webhook urls
      * @var string[]
      */
    protected $urls;
    
    /**
      * $username Optional HTTP Basic Auth username
      * @var string
      */
    protected $username;
    
    /**
      * $password Optional HTTP Basic Auth password
      * @var string
      */
    protected $password;
    
    /**
      * $disabled Webhook disabled
      * @var bool
      */
    protected $disabled = false;
    
    /**
      * $alert_emails Optional list of emails to send alert to if webhook fails
      * @var string[]
      */
    protected $alert_emails;
    
    /**
      * $alert_count Number of requests to perform before alert email is sent, must be greater than or equal to four (1 hour)
      * @var int
      */
    protected $alert_count;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->urls = $data["urls"];
            $this->username = $data["username"];
            $this->password = $data["password"];
            $this->disabled = $data["disabled"];
            $this->alert_emails = $data["alert_emails"];
            $this->alert_count = $data["alert_count"];
        }
    }
    
    /**
     * Gets urls
     * @return string[]
     */
    public function getUrls()
    {
        return $this->urls;
    }
  
    /**
     * Sets urls
     * @param string[] $urls Webhook urls
     * @return $this
     */
    public function setUrls($urls)
    {
        
        $this->urls = $urls;
        return $this;
    }
    
    /**
     * Gets username
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }
  
    /**
     * Sets username
     * @param string $username Optional HTTP Basic Auth username
     * @return $this
     */
    public function setUsername($username)
    {
        
        $this->username = $username;
        return $this;
    }
    
    /**
     * Gets password
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }
  
    /**
     * Sets password
     * @param string $password Optional HTTP Basic Auth password
     * @return $this
     */
    public function setPassword($password)
    {
        
        $this->password = $password;
        return $this;
    }
    
    /**
     * Gets disabled
     * @return bool
     */
    public function getDisabled()
    {
        return $this->disabled;
    }
  
    /**
     * Sets disabled
     * @param bool $disabled Webhook disabled
     * @return $this
     */
    public function setDisabled($disabled)
    {
        
        $this->disabled = $disabled;
        return $this;
    }
    
    /**
     * Gets alert_emails
     * @return string[]
     */
    public function getAlertEmails()
    {
        return $this->alert_emails;
    }
  
    /**
     * Sets alert_emails
     * @param string[] $alert_emails Optional list of emails to send alert to if webhook fails
     * @return $this
     */
    public function setAlertEmails($alert_emails)
    {
        
        $this->alert_emails = $alert_emails;
        return $this;
    }
    
    /**
     * Gets alert_count
     * @return int
     */
    public function getAlertCount()
    {
        return $this->alert_count;
    }
  
    /**
     * Sets alert_count
     * @param int $alert_count Number of requests to perform before alert email is sent, must be greater than or equal to four (1 hour)
     * @return $this
     */
    public function setAlertCount($alert_count)
    {
        
        $this->alert_count = $alert_count;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
